function loadruleScreen()
    font3 = love.graphics.newFont('PixelGame-R9AZe.otf', 40)
    meat = love.graphics.newImage('meat.png')
    water = love.graphics.newImage('water.png')
    sushi = love.graphics.newImage('sushi.png')
    burger = love.graphics.newImage("burger.png")
    milk = love.graphics.newImage('milk.png')
    taco = love.graphics.newImage('taco.png')
    dumpling = love.graphics.newImage('dumpling.png')
    pizza = love.graphics.newImage('pizza.png')
    candy = love.graphics.newImage('candy.png')
    pepper = love.graphics.newImage('pepper.png')
    pineapple = love.graphics.newImage('pineapple.png')
    tomato = love.graphics.newImage('tomato.png')

end

function updateruleScreen(dt)
    
end

function drawruleScreen()
    love.graphics.setColor(0,0,0)
    love.graphics.setFont(font3)
    love.graphics.scale(1, 1)
    love.graphics.print("Isha LOVES:", love.graphics.getWidth() / 2 - 200 , love.graphics.getHeight() / 2 - 100)
    love.graphics.setColor(1,1,1)
    love.graphics.push()
    love.graphics.scale(0.8,0.8) 
    love.graphics.draw(meat, love.graphics.getWidth() / 2 + 40, love.graphics.getHeight() / 2 - 77)
    love.graphics.draw(water, love.graphics.getWidth() / 2 + 95, love.graphics.getHeight() / 2 - 70)
    love.graphics.draw(sushi, love.graphics.getWidth() / 2 + 155, love.graphics.getHeight() / 2 - 55)
    love.graphics.draw(burger, love.graphics.getWidth() / 2 + 205, love.graphics.getHeight() / 2 - 63)
    love.graphics.pop() 
    
    love.graphics.setColor(0,0,0)
    love.graphics.print("Isha LIKES:", love.graphics.getWidth() / 2 - 200, love.graphics.getHeight() / 2 - 40)
    love.graphics.setColor(1,1,1)
    love.graphics.push()
    love.graphics.scale(0.8, 0.8) 
    love.graphics.draw(milk, love.graphics.getWidth() / 2 + 40, love.graphics.getHeight() / 2 + 10)
    love.graphics.draw(taco, love.graphics.getWidth() / 2 + 100, love.graphics.getHeight() / 2 + 10)
    love.graphics.draw(dumpling, love.graphics.getWidth() / 2 + 155, love.graphics.getHeight() / 2)
    love.graphics.draw(pizza, love.graphics.getWidth() / 2 + 240, love.graphics.getHeight() / 2 + 15)
    love.graphics.draw(candy, love.graphics.getWidth() / 2 + 300, love.graphics.getHeight() / 2 + 15)
    love.graphics.pop()

    love.graphics.setColor(0,0,0)
    love.graphics.print("Isha HATES:", love.graphics.getWidth() / 2 - 200, love.graphics.getHeight() / 2 + 20)
    love.graphics.setColor(1,1,1)
    love.graphics.draw(pepper, love.graphics.getWidth() / 2 - 35, love.graphics.getHeight() / 2 + 10)
    love.graphics.push()
    love.graphics.scale(0.9, 0.9) 
    love.graphics.draw(pineapple, love.graphics.getWidth() / 2 + 50, love.graphics.getHeight() / 2 + 38)
    love.graphics.draw(tomato, love.graphics.getWidth() / 2 + 107, love.graphics.getHeight() / 2 + 47)

    love.graphics.pop()
    love.graphics.setColor(1,0,0)
    love.graphics.print("Press Space to Start!", love.graphics.getWidth() / 2 - 178, love.graphics.getHeight() / 2 + 100)
    love.graphics.setColor(1,1,1)
end